project_id = "nvinlpcdiygiedddxeih"

[functions.fetch-response-sheet]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-seed-tests]
verify_jwt = false

[functions.upload-answer-keys]
verify_jwt = false

[functions.score-submission]
verify_jwt = false
 
 [functions.admin-fetch-tests]
 verify_jwt = false
 
 [functions.admin-manage-tests]
 verify_jwt = false

[functions.upload-question-paper]
verify_jwt = false
